/**
 * Preview data emitter — converts a `Palette` into shell-sourceable RGB
 * triples for use by `assets/preview.sh`.
 *
 * Why this exists: `preview.sh` needs the exact palette colors as 24-bit
 * true-color escape codes so the screenshots are pixel-perfect regardless
 * of the active iTerm2 profile. Hardcoding hex/RGB values in the shell
 * script would duplicate the source of truth in `src/palette/*.ts` and
 * violate the project invariant that hex literals live exclusively in
 * the palette layer (see AGENTS.md → "Архитектурные инварианты").
 *
 * Build flow: `build.ts` calls `paletteToShell` for each variant and
 * concatenates the results into `assets/_preview-data.sh`. `preview.sh`
 * sources that file and uses a case statement on the variant argument
 * to select the active palette.
 *
 * No I/O, no logging, no globals. Throws via `parseHexBytes` on invalid
 * palette hex (which would also fail the build at the render boundary).
 */

import { parseHexBytes } from "./color.ts";
import type { Palette } from "../palette/types.ts";

/**
 * Map from short shell-friendly suffixes to the corresponding palette cell.
 *
 * The order here defines the emitted line order in `_preview-data.sh`.
 * Suffixes are kept terse (`RED`, `GRN`, `BR_BLU`, …) because they appear
 * many times in `preview.sh` printf calls — readability there benefits more
 * than the generated data file.
 */
type Cell = {
  readonly suffix: string;
  readonly hex: (p: Palette) => string;
};

const CELLS: ReadonlyArray<Cell> = [
  // UI-derived
  { suffix: "FG", hex: (p) => p.ui.foreground },
  { suffix: "HLT", hex: (p) => p.ui.link },
  // ANSI 0–7
  { suffix: "BLK", hex: (p) => p.ansi.black },
  { suffix: "RED", hex: (p) => p.ansi.red },
  { suffix: "GRN", hex: (p) => p.ansi.green },
  { suffix: "YEL", hex: (p) => p.ansi.yellow },
  { suffix: "BLU", hex: (p) => p.ansi.blue },
  { suffix: "MAG", hex: (p) => p.ansi.magenta },
  { suffix: "CYA", hex: (p) => p.ansi.cyan },
  { suffix: "WHT", hex: (p) => p.ansi.white },
  // ANSI 8–15
  { suffix: "GRY", hex: (p) => p.ansi.brightBlack },
  { suffix: "BR_RED", hex: (p) => p.ansi.brightRed },
  { suffix: "BR_GRN", hex: (p) => p.ansi.brightGreen },
  { suffix: "BR_YEL", hex: (p) => p.ansi.brightYellow },
  { suffix: "BR_BLU", hex: (p) => p.ansi.brightBlue },
  { suffix: "BR_MAG", hex: (p) => p.ansi.brightMagenta },
  { suffix: "BR_CYA", hex: (p) => p.ansi.brightCyan },
  { suffix: "BR_WHT", hex: (p) => p.ansi.brightWhite },
];

/**
 * Render a single palette as a block of shell variable assignments.
 *
 * Output shape (one variable per line, three components each):
 *
 * ```
 * # Karma Dark
 * DARK_FG_R=247; DARK_FG_G=241; DARK_FG_B=255   # #f7f1ff
 * DARK_HLT_R=168; DARK_HLT_G=110; DARK_HLT_B=253   # #a86efd
 * ...
 * ```
 *
 * The trailing hex comment lets a maintainer eyeball the palette without
 * cross-referencing `src/palette/*.ts`. The comment is not parsed by bash.
 *
 * @param palette - Palette to emit.
 * @param prefix - Shell variable prefix (e.g. `"DARK"`, `"DARK_HC"`). Conventionally
 *   uppercase ASCII without trailing underscore — the function adds it.
 * @returns Multi-line string, no trailing newline.
 */
export function paletteToShell(palette: Palette, prefix: string): string {
  const lines: string[] = [`# ${palette.name}`];

  for (const { suffix, hex } of CELLS) {
    const colorHex = hex(palette);
    const { r, g, b } = parseHexBytes(colorHex);
    const base = `${prefix}_${suffix}`;
    lines.push(`${base}_R=${r}; ${base}_G=${g}; ${base}_B=${b}   # ${colorHex}`);
  }

  return lines.join("\n");
}

/**
 * Render multiple palettes into a single `_preview-data.sh` document with
 * a header comment marking the file as auto-generated.
 *
 * @param entries - Mapping from shell prefix to palette.
 * @returns Full file contents (with trailing newline).
 */
export function renderPreviewData(
  entries: ReadonlyArray<{ readonly prefix: string; readonly palette: Palette }>,
): string {
  const header = [
    "#!/usr/bin/env bash",
    "#",
    "# AUTO-GENERATED by build.ts — do not edit by hand.",
    "# Source of truth: src/palette/*.ts via src/render/preview-data.ts.",
    "#",
    "# This file is sourced by assets/preview.sh; it defines RGB triples for",
    "# every Karma variant so the preview output is pixel-perfect regardless",
    "# of the active iTerm2 profile.",
    "",
    "",
  ].join("\n");

  const blocks = entries.map((e) => paletteToShell(e.palette, e.prefix));
  return header + blocks.join("\n\n") + "\n";
}
